export const CHARS_PER_TOKEN = 4;
export const SAFETY_MARGIN = 0.95;
export const EXPECTED_OUTPUT_TOKENS_DEFAULT = 4096;
export const SAFE_TOKEN_UTILIZATION_PERCENTAGE = 80
export const WARNING_TOKEN_UTILIZATION_PERCENTAGE = 95